// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_Wk7Sho15HMF_4EV5VO_VTGar8UJt6cY',
    appId: '1:870788251446:web:afac4c1191498461f03d97',
    messagingSenderId: '870788251446',
    projectId: 'flutterproject-ffa57',
    authDomain: 'flutterproject-ffa57.firebaseapp.com',
    storageBucket: 'flutterproject-ffa57.firebasestorage.app',
    measurementId: 'G-8XEPL3HGN4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA-lgvXK2Lw8boVSfSgJv5PXN2P4Kvep0',
    appId: '1:870788251446:android:cadc20b0e60a0526f03d97',
    messagingSenderId: '870788251446',
    projectId: 'flutterproject-ffa57',
    storageBucket: 'flutterproject-ffa57.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUqx-mD4i0Fr30g-MNRb_E9WPqWZiqpio',
    appId: '1:870788251446:ios:49b28b4213ca81ccf03d97',
    messagingSenderId: '870788251446',
    projectId: 'flutterproject-ffa57',
    storageBucket: 'flutterproject-ffa57.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUqx-mD4i0Fr30g-MNRb_E9WPqWZiqpio',
    appId: '1:870788251446:ios:49b28b4213ca81ccf03d97',
    messagingSenderId: '870788251446',
    projectId: 'flutterproject-ffa57',
    storageBucket: 'flutterproject-ffa57.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_Wk7Sho15HMF_4EV5VO_VTGar8UJt6cY',
    appId: '1:870788251446:web:bfdd42abf18a6671f03d97',
    messagingSenderId: '870788251446',
    projectId: 'flutterproject-ffa57',
    authDomain: 'flutterproject-ffa57.firebaseapp.com',
    storageBucket: 'flutterproject-ffa57.firebasestorage.app',
    measurementId: 'G-99JC13D07K',
  );
}
